name: solar_location_validation
version: 1.0.1+2
description: A new Flutter project.
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  camera: ^0.5.7+3
  sensors: ^0.4.1+7
  image_picker: ^0.6.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
